// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file bucket/bucket.proto (package bucket, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ReaddirRequest, ReaddirResponse, RemoveRequest, RemoveResponse, SignedURLRequest, SignedURLResponse } from "./bucket_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bucket.BucketService
 */
export const BucketService = {
  typeName: "bucket.BucketService",
  methods: {
    /**
     * @generated from rpc bucket.BucketService.SignedURL
     */
    signedURL: {
      name: "SignedURL",
      I: SignedURLRequest,
      O: SignedURLResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bucket.BucketService.Readdir
     */
    readdir: {
      name: "Readdir",
      I: ReaddirRequest,
      O: ReaddirResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bucket.BucketService.Remove
     */
    remove: {
      name: "Remove",
      I: RemoveRequest,
      O: RemoveResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

