version: '3.6'
services:
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: password
#      PGDATA: /var/lib/postgresql/data/db
#    ports:
#      - 5432:5432
#    volumes:
#      - db:/var/lib/postgresql/data/db
#    labels:
#      kompose.service.type: clusterip
#      kompose.volume.type: persistentVolumeClaim
#
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 3000:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con2,con4

      LABEL_con2: Postgres
      SERVER_con2: postgres
      USER_con2: postgres
      PASSWORD_con2: TEST
      PORT_con2: 5432
      ENGINE_con2: postgres@dbgate-plugin-postgres

      LABEL_con4: SQLite
      FILE_con4: /home/breadchris/.lunabrain/db.sqlite
      ENGINE_con4: sqlite@dbgate-plugin-sqlite

  postgres:
    # Special image with vectorized postgres
    image: ankane/pgvector:v0.4.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  dbgate-data:
    driver: local
  db:
