openai:
  api_key: test
api:
  local: true
scrape:
  client: chrome
  fallback: true
  use_cache: true
python:
  host: 'lunabrain-python:50051'
normalize:
  url:
    domain_content: true
youtube:
  api_key: TODO
discord:
  application_id: 1090552222460424204
  token: MTA5MDU1MjIyMjQ2MDQyNDIwNA.GK-s90.OHvvW-HvtOnJzYrWmKzKTvKcfSMXqX1O3QbGXY
publish:
  discord:
    enabled: false
    channel_id: 1080517727715860581
