openai:
  api_key: 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
api:
  local: true
scrape:
  client: chrome
  fallback: true
  use_cache: false
python:
  host: 'lunabrain-python:50051'
normalize:
  url:
    domain_content: true
youtube:
  api_key: TODO
discord:
  application_id: 1090552222460424204
  token: MTA5MDU1MjIyMjQ2MDQyNDIwNA.GWJ2lA.8GiPrDL9AQZEmLtsRGf7r2eNQhF-X5NYkBM8fI
publish:
  discord:
    enabled: false
    channel_id: 1080517727715860581
