version: '3.6'
services:
  justshare:
#    image: ghcr.io/justshare/justshare
    build:
      context: ..
    hostname: justshare
    ports:
      - "80:8080"
    volumes:
      - ./data:/data
      - ./config:/app/config
    restart: always
    profiles:
      - base

  postgres:
    # Special image with vectorized postgres
    image: ankane/pgvector:v0.4.0
    restart: always
    profiles:
      - base
    ports:
      - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    labels:
      kompose.service.type: clusterip
      kompose.volume.type: persistentVolumeClaim
volumes:
  db:
