apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunabrain-python
  labels:
    app: lunabrain-python
spec:
  selector:
    matchLabels:
      app: lunabrain-python
  template:
    metadata:
      labels:
        app: lunabrain-python
    spec:
      containers:
      - name: lunabrain-python
        image: lunabrain-python-image
        env:
          - name: OPENAI_API_KEY
            value: "test"
          - name: LUNABRAIN_DIR
            value: "/tmp"
        ports:
        - containerPort: 50051
        volumeMounts:
          - mountPath: /app/config/lunabrain
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: lunabrain-config
