// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file deploy/service.proto (package deploy, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeployRequest, DeployResponse } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service deploy.DeployService
 */
export const DeployService = {
  typeName: "deploy.DeployService",
  methods: {
    /**
     * @generated from rpc deploy.DeployService.Deploy
     */
    deploy: {
      name: "Deploy",
      I: DeployRequest,
      O: DeployResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

