name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.8.0
        with:
          setup-tools: |
            yq
          yq: "4.16.2"

      - name: Docker Build
        run: docker build . -t justshare

      - if: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        run: exit 0

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image
        if: github.ref == 'refs/heads/main'
        run: |
          SERVER_IMAGE_ID=ghcr.io/justshare-io/justshare

          # Change all uppercase to lowercase
          SERVER_IMAGE_ID=$(echo $SERVER_IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo SERVER_IMAGE_ID=$SERVER_IMAGE_ID
          echo VERSION=$VERSION

          docker tag justshare $SERVER_IMAGE_ID:$VERSION
          docker push $SERVER_IMAGE_ID:$VERSION

          yq -i e ".services.justshare.image |= \"$(docker inspect --format='{{index .RepoDigests 0}}' $SERVER_IMAGE_ID:$VERSION)\"" docker-compose.prod.yaml
